name: Google Functions

on:
  push:
    branches:
      - hotFix/ci

env:
  FUNCTION_ENV: ${{ secrets.FUNCTION_ENV }}
  GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_SA_PROJECT_ID: ${{ secrets.GCP_SA_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: deploy
        run: |
          echo $FUNCTION_ENV | base64 -d > env.yaml
          gcloud functions deploy stock-clawler --project $GCP_SA_PROJECT_ID --quiet --entry-point=main --trigger-topic=stock --env-vars-file=env.yaml --source=src --runtime=python38 --timeout=300
